### ISSUE TITLE
Add CI

### ISSUE THREAD

**Issue by donhardman** [manticoresoftware/manticoresearch-text-embeddings#4]
We should consider adding CI that will run tests, build all given packages, and deploy them to the repository.

To make it easier, we should research and look into ways to build it statically for easier linking in different operating systems.

**Comment by sanikolaev** [comment]
As decided on today's call, let's move the code from this repo to https://github.com/manticoresoftware/columnar to simplify the building process.

**Comment by donhardman** [comment]
Done in this pull request: https://github.com/manticoresoftware/columnar/pull/74
