### ISSUE TITLE
Function to return library version in verbose mode

### ISSUE THREAD

**Issue by sanikolaev** [manticoresoftware/manticoresearch-text-embeddings#8]
As discussed during today's dev call, we need to add a function to the library for versioning. This function should return something like `1.2.3 <date> <commit>`, similar to how other MCL libraries handle it.

**Comment by donhardman** [comment]
As discussed previously, it's a bit tricky to automatically add dates or commits at this time. However, we should consider implementing this when we build the CI.

Implementation available here: https://github.com/manticoresoftware/manticoresearch-text-embeddings/pull/9
